### ISSUE TITLE
Add an option in the configuration file to disable playername history

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [Jikoo/OpenInv#107]
I switched from EssentialsX's `/invsee` and `/endersee` to this plugin because that plugin can't view offline player's inventories and enderchests (see [here](https://github.com/EssentialsX/Essentials/issues/98)). Some of those coming from EssX like me might want the command `/openinv` and `/openender` to not remember their last executed playername, just like EssentialsX's `/invsee` command behavior as some of my staff reported that the history feature is kinda annoying to use.

**Comment by QuanTrieuPCYT** [comment]
A new config entry called `disable-playername-history` in the `config.yml` file should be ideal.

**Comment by Jikoo** [comment]
I would have to also include a better search -> user cache system for me to be comfortable with removing history. As it is, any parameterized location without an exact match online loads all offline players. Using the no-parameter command actually retrieves the last opened player much faster for offline players because it fetches them directly by UUID.
