### ISSUE TITLE
Title of inventory/enderchest GUI shows name of the player executing command, not targeted player

### ISSUE THREAD

**Issue by takatalvi** [Jikoo/OpenInv#13]
Hi, I've noticed that since last version, the GUI always shows the name of the player who runs the /oi or /oe command, not the targeted player. In messages YMLs the variable is called %player%, I think this value should be populated by the targeted player. Thanks!

**Comment by Jikoo** [comment]
Dev builds aren't quite as easy to grab as they would be off a standard CI, but due to the NMS dependency I'm too lazy to set up Appveyor/other. You can instead grab the `dist` zip file artifact off a successful Actions run (such as [this](https://github.com/Jikoo/OpenInv/actions/runs/695312585) ) and unzip it to obtain a compiled dev build of OpenInv.
