### ISSUE TITLE
Broken with Magma Forge Server

### ISSUE THREAD

**Issue by Relaxing9** [Jikoo/OpenInv#140]
OpenInv Version: 4.3.0
Server Version: Magma version 1.18.2-43e59c84 (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.1)

From Logs: https://paste.gg/p/anonymous/56ce379337a24e9ca72f0475d8f9c2b1
From Console: https://paste.gg/p/anonymous/0d773276a7b844a89acdd1408a9b5420 

![image](https://user-images.githubusercontent.com/41935047/233785792-456f1605-2693-4be0-9ec8-0ebc754a3596.png)

Anytime the commands openinv and openender are ran on a Forge server there is an error, and the intended result doesn't happen just an error.

**Comment by Jikoo** [comment]
OI requires Spigot internals. I highly recommend you run a Forge mod for things like this; OI does not have support for concepts like dynamic additional inventory slots e.g. Baubles or whatever the modern equivalent is. These combo servers have also been notoriously unreliable because mods have a tendency to accomplish their goals in various inconsistent ways that result in missed cases for Bukkit events and whatnot.

Re: what I am assuming is a response from a Magma dev: They can add a [Commodore](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/Commodore.java) entry to remap methods when loading plugins. It does require them to manually maintain the bytecode rewrite, but that's about it. The CB plugin loader that I assume they're piggybacking should handle the rest.
