### ISSUE TITLE
Crashing on paper 1.21

### ISSUE THREAD

**Issue by fandasliz** [Jikoo/OpenInv#232]
Hello,
after updating server to minecraft version 1.21 using paper 1.21 (123) our server started crashing. We use OpenInv version 5.0.0.
Server stopped responding multiple times right after opening enderchest through /openender or /oe resulting in crash. We are using /oe multiple times without any problems but sometimes it causes the server to stop responding once or two times per day randomly after typing /oe.
Attached is crash log from paper. Thanks for any help or advice.
[2024-08-04-4.log](https://github.com/user-attachments/files/16488420/2024-08-04-4.log)

**Comment by Jikoo** [comment]
Looks like shift clicking to/from an /openender enderchest. Do you happen to have any idea what the contents were or which slot was clicked?

**Comment by fandasliz** [comment]
Sorry don't know if player clicked on any slots it seemed like it stopped responding immediately after typing /oe. I found ender chest contains. I tried to reproduce it but had no success. Thanks for answer.
![image](https://github.com/user-attachments/assets/219d355d-1a98-425c-a895-16843affed85)
![image](https://github.com/user-attachments/assets/89ba4e12-8ab3-4959-bfdf-dd4a8e08b85b) - custom decorated pot

**Comment by Jikoo** [comment]
Hm, okay, thank you either way, that gives me a setup to poke around with. The trace does indicate that they shift-clicked something, but both the top and bottom are vanilla menu slots in the ender chest menu, so it can't be narrowed down further without being able to reproduce or get in touch with the player.

The weird part is that the traces don't point deeper into the backing container, because the method being called should just be a direct call to the backing container's content.

**Comment by fandasliz** [comment]
After further testing I figured out that shift clicking stone into full /oe stopped server from responding every time I tried that. Seems like it doesn't matter at which slot stone was as long as ender chest was full and I shift clicked more stone from inventory.
Thanks again for answer.
Inv example:
![image](https://github.com/user-attachments/assets/408eeb3c-b3b8-48a0-8b4b-240d0300fa3d)

**Comment by Jikoo** [comment]
Thank you for the assistance, particularly the screenshots. I was struggling to reproduce consistently despite knowing what the cause was after doing a little debugging. Turns out there was a second mistake causing the final slot to overwrite the result of the shift click, so only the item in the final slot of the inventory causes the freeze.
