### ISSUE TITLE
Onlining player during editing not functioning properly

### ISSUE THREAD

**Issue by JHarris12345** [Jikoo/OpenInv#246]
If you are editing an offline player's inventory and they come online mid-edit, you are no longer editing their inventory

**Comment by Jikoo** [comment]
Could I get your server and OpenInv /version please? I probably won't have time to dig into this until the weekend, but that way I can at least be ready.

**Comment by JHarris12345** [comment]
Plugin ver is 5.1.1 and server ver is 1.21.1

**Comment by Jikoo** [comment]
1.21.1 is a Minecraft version, not a Bukkit server implementation version.
In this case /version is really important, because this is a problem I had already encountered and solved during the 1.21 update. If this is a Paper server I need to check whether it occurs on Spigot or if it's a Paper-specific problem so I can look at the correct areas. The commit hashes (or build number for Paper) included in the output of /version are also useful for determining what changes may have been made by the server implementation since I last verified functionality, which allows me to track down where a problem might be occurring way faster.

**Comment by Jikoo** [comment]
https://github.com/Jikoo/OpenInv/releases/tag/5.1.2
