### ISSUE TITLE
Can't use the commands

### ISSUE THREAD

**Issue by Phragonality** [Jikoo/OpenInv#28]
Hello People,

I'm using apex hosting and I installed this plugin to my server just by clicking install on the apex plugin area. I restarted my server after that and logged in, but for some reason the commands don't work. I am opped and everything but it still doesn't work. Idk if having another plugin affects it (which I do) or if I'm just being stupid. Does anyone know if I had to do something with my minecraft files or the server files? Could anyone please help me out? This plug-in is essential to my server because of a few friends of mine. Someone please help me.

-Phragonality

**Comment by Jikoo** [comment]
Update Spigot.

**Comment by Jikoo** [comment]
I realize on a reread that your issue is slightly different from the 3 other people presumably also using Apex with outdated server jars, however, I'm not going to reopen until you provide the output of `/version` and `/version OpenInv` - frankly, seems like Apex Hosting is very crappy about updating the builds they offer per [this comment](https://dev.bukkit.org/projects/openinv#c1485).
